### PR TITLE
fix: rounding of ideal burndown to 2 decimal places

### LINKED ISSUE #10: Rounding error causes points to drop below 0
Due to rounding errors, in certain cases, the points on the last day may be less than 0, causing the graph to include the negative y-axis

Example graph:
sprint4-latest-burndown

Log output:
```
{"MODE":"manual"}
{"message":"Found latest sprint","sprint":4,"start":"2021-08-24T00:00:00.000Z","end":"2021-09-07T00:00:00.000Z"}
{"message":"Counted points left in sprint","sprint":4,"pointsLeftIn***":107}
{"message":"Updated daily summary table","sprint":4,"pointsLeftIn***":107}
{"numDaysSince***Start":3}
{"initialPoints":112,"numberOfWeekdays":10,"pointsPerDay":11.2}
{"labels":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],"data":[112,112,107,107],"idealBurndown":[112,100.8,89.6,78.39999999999999,67.19999999999999,67.19999999999999,67.19999999999999,55.999999999999986,44.79999999999998,33.59999999999998,22.39999999999998,11.199999999999982,11.199999999999982,11.199999999999982,-1.7763568394002505e-14]}
{"message":"Generated burndown chart","sprint":4,"data":[112,112,107,107]}
```

### PR DESCRIPTION
**Pull request by jedidiahkkh**
fixes: #10

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -232,7 +232,9 @@ const getIdealBurndown = (start, end, initialPoints, numberOfWeekdays) => {
     isPrevDayWeekday = !isWeekend(cur);
   }
 
-  return idealBurndown;
+  // rounds to 2 decimal places, which prevents the graph from getting jagged
+  // from overtruncation when there's less than 30 points
+  return idealBurndown.map(points => Math.round(points*100)/100);
```
Comment (szenius) [inline src/index.js]: Hmm what about doing this instead? : https://stackoverflow.com/a/12830454

Would be a lot more readable

**Review by szenius — APPROVED** [review]
Thank you for working on this!
